title: Rustambek Oripov
email: herofirst4464@gmail.com
description: "Rustambek Oripov â€” Java Backend Developer | Spring Boot | Microservices"
lang: uz
# For project pages: https://lion4464.github.io
url: "https://lion4464.github.io"
baseurl: ""
